package main

//go:generate go run . gendocs

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"regexp"
	"strings"

	"github.com/urfave/cli/v3"
)

const generatedHeader = `<!-- Code generated by "go generate"; DO NOT EDIT. Source: schema.go -->`

// genTarget is a documentation file kept in sync with the source. Render
// receives the file's current content (used by marker-injected targets) and
// returns the up-to-date content. The gendocs command writes the result;
// TestGeneratedDocsUpToDate fails when it differs from what is committed.
type genTarget struct {
	Path   string
	Render func(current []byte) ([]byte, error)
}

func genTargets() []genTarget {
	return []genTarget{
		{
			Path:   ".claude/skills/hocage/references/event-types-and-output.md",
			Render: func([]byte) ([]byte, error) { return generateEventDocs(), nil },
		},
	}
}

func gendocsCommand() *cli.Command {
	return &cli.Command{
		Name:   "gendocs",
		Usage:  "Regenerate docs derived from the source (run via go generate)",
		Hidden: true,
		Action: gendocsAction,
	}
}

func gendocsAction(ctx context.Context, cmd *cli.Command) error {
	for _, tgt := range genTargets() {
		current, err := os.ReadFile(tgt.Path)
		if err != nil {
			return fmt.Errorf("gendocs must run from the repo root: %w", err)
		}
		want, err := tgt.Render(current)
		if err != nil {
			return fmt.Errorf("%s: %w", tgt.Path, err)
		}
		if bytes.Equal(current, want) {
			continue
		}
		if err := os.WriteFile(tgt.Path, want, 0o644); err != nil {
			return err
		}
		fmt.Fprintf(os.Stderr, "updated %s\n", tgt.Path)
	}
	return nil
}

// injectSection replaces the text between "<!-- gen:NAME:start -->" and
// "<!-- gen:NAME:end -->" in content with gen, keeping the markers.
func injectSection(content []byte, name string, gen []byte) ([]byte, error) {
	start := fmt.Sprintf("<!-- gen:%s:start -->", name)
	end := fmt.Sprintf("<!-- gen:%s:end -->", name)
	re := regexp.MustCompile(`(?s)` + regexp.QuoteMeta(start) + `.*?` + regexp.QuoteMeta(end))
	if !re.Match(content) {
		return nil, fmt.Errorf("markers %s / %s not found", start, end)
	}
	replacement := start + "\n" + string(bytes.TrimSpace(gen)) + "\n" + end
	return re.ReplaceAll(content, []byte(replacement)), nil
}

func generateEventDocs() []byte {
	var b strings.Builder
	b.WriteString(generatedHeader + "\n")
	b.WriteString("# Event Types and Output Schemas\n\n")
	b.WriteString("The authoritative reference for all hocage event types and their respond output schemas.\n\n")

	b.WriteString(`## hookSpecificOutput

Many events accept a ` + "`hookSpecificOutput`" + ` object for event-specific output (see each
event section below for its nested fields). Inside it, ` + "`hookEventName`" + ` must exactly
match the event name that triggered the hook (e.g. ` + "`PreToolUse`" + `). ` + "`hocage hooks check`" + `
validates nested fields, types, and enum values, using dotted paths in error messages
(e.g. ` + "`hookSpecificOutput.permissionDecision`" + `).

`)

	b.WriteString("## Events with Output Fields\n\n")
	for _, ev := range eventDefs {
		if len(ev.Fields) == 0 {
			continue
		}
		fmt.Fprintf(&b, "### %s\n\n%s\n\n", ev.Name, ev.Doc)
		writeFieldTableHeader(&b)
		for _, f := range ev.Fields {
			writeFieldRow(&b, "", f, false)
		}
		b.WriteString("\n")
		for _, f := range ev.Fields {
			if f.Name == "hookSpecificOutput" {
				b.WriteString("`hookSpecificOutput` nested fields:\n\n")
				writeFieldTableHeader(&b)
				for _, nested := range f.Fields {
					writeFieldRow(&b, "", nested, true)
				}
				b.WriteString("\n")
			}
		}
		if ev.Example != "" {
			b.WriteString(ev.Example)
			b.WriteString("\n\n")
		}
	}

	b.WriteString(`## Events with No Output Fields

These events are observe-only. Use them with ` + "`command` or `http`" + ` actions (not
` + "`respond`" + `), or use ` + "`respond`" + ` with an empty object.

| Event | Description |
|-------|-------------|
`)
	for _, ev := range eventDefs {
		if len(ev.Fields) == 0 {
			fmt.Fprintf(&b, "| `%s` | %s |\n", ev.Name, ev.Doc)
		}
	}
	b.WriteString("\n")

	b.WriteString(`## Event Input Structure

All events receive a JSON object on stdin with at minimum:
` + fence + `json
{ "hook_type": "<EventName>" }
` + fence + `

Tool events (PreToolUse, PostToolUse, etc.) also include:
` + fence + `json
{
  "hook_type": "PreToolUse",
  "tool_name": "Bash",
  "tool_input": { "command": "ls -la" }
}
` + fence + `

UserPromptSubmit includes:
` + fence + `json
{
  "hook_type": "UserPromptSubmit",
  "prompt": "the user's prompt text"
}
` + fence + `

Access these via ` + "`event.hook_type`, `event.tool_name`, `event.tool_input.command`" + `, etc. in CEL expressions.
`)

	return []byte(b.String())
}

func writeFieldTableHeader(b *strings.Builder) {
	b.WriteString("| Field | Type | Allowed Values | Description |\n")
	b.WriteString("|-------|------|----------------|-------------|\n")
}

// writeFieldRow writes one table row. When flatten is true, object fields with
// a nested schema also emit their children as dotted-path rows (e.g.
// decision.behavior); otherwise nested schemas are summarized as "see below".
func writeFieldRow(b *strings.Builder, prefix string, f FieldDef, flatten bool) {
	name := prefix + f.Name
	fmt.Fprintf(b, "| `%s` | %s | %s | %s |\n", name, f.Type, allowedValues(f), f.Doc)
	if flatten && f.Fields != nil {
		for _, nested := range f.Fields {
			writeFieldRow(b, name+".", nested, true)
		}
	}
}

func allowedValues(f FieldDef) string {
	switch {
	case len(f.Enum) > 0:
		vals := make([]string, len(f.Enum))
		for i, v := range f.Enum {
			vals[i] = "`" + v + "`"
		}
		return strings.Join(vals, ", ")
	case f.Type == FieldTypeBool:
		return "`true`/`false`"
	case f.Fields != nil:
		return "see below"
	default:
		return "any"
	}
}
