package main

//go:generate go run . gendocs

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"regexp"
	"slices"
	"strings"

	"github.com/google/cel-go/cel"
	"github.com/urfave/cli/v3"
)

func generatedHeader(source string) string {
	return fmt.Sprintf(`<!-- Code generated by "go generate"; DO NOT EDIT. Source: %s -->`, source)
}

// genTarget is a documentation file kept in sync with the source. Render
// receives the file's current content (used by marker-injected targets) and
// returns the up-to-date content. The gendocs command writes the result;
// TestGeneratedDocsUpToDate fails when it differs from what is committed.
type genTarget struct {
	Path   string
	Render func(current []byte) ([]byte, error)
}

func genTargets() []genTarget {
	return []genTarget{
		{
			Path:   ".claude/skills/hocage/references/event-types-and-output.md",
			Render: func([]byte) ([]byte, error) { return generateEventDocs(), nil },
		},
		{
			Path:   ".claude/skills/hocage/references/cel-functions.md",
			Render: func([]byte) ([]byte, error) { return generateCELFunctionDocs() },
		},
		{
			Path: "README.md",
			Render: func(current []byte) ([]byte, error) {
				out, err := injectSection(current, "cli", generateCLIDocs())
				if err != nil {
					return nil, err
				}
				names, err := customCELFunctions()
				if err != nil {
					return nil, err
				}
				out, err = injectSection(out, "cel-functions", formatCELFunctionList(names))
				if err != nil {
					return nil, err
				}
				return injectSection(out, "cel-extensions", formatStdExtList())
			},
		},
		{
			Path: ".claude/skills/hocage/SKILL.md",
			Render: func(current []byte) ([]byte, error) {
				return injectSection(current, "cli-table", generateCLITable())
			},
		},
	}
}

// generateCLIDocs renders the full CLI reference for the README: one section
// per leaf command with its Usage, Description (verbatim), and flags.
func generateCLIDocs() []byte {
	app := newApp()
	var b strings.Builder
	b.WriteString("Global flags:\n\n")
	writeFlagLines(&b, app.Flags)
	b.WriteString("\n")
	walkLeafCommands("hocage", app.VisibleCommands(), func(name string, c *cli.Command) {
		fmt.Fprintf(&b, "### `%s`\n\n%s.\n\n", name, strings.TrimSuffix(c.Usage, "."))
		if c.Description != "" {
			b.WriteString(c.Description)
			b.WriteString("\n\n")
		}
		if len(c.Flags) > 0 {
			b.WriteString("Flags:\n\n")
			writeFlagLines(&b, c.Flags)
			b.WriteString("\n")
		}
	})
	return []byte(strings.TrimSpace(b.String()) + "\n")
}

// walkLeafCommands calls visit for every visible leaf command, passing the full
// command path (with ArgsUsage appended when present).
func walkLeafCommands(prefix string, cmds []*cli.Command, visit func(name string, c *cli.Command)) {
	for _, c := range cmds {
		name := prefix + " " + c.Name
		if sub := c.VisibleCommands(); len(sub) > 0 {
			walkLeafCommands(name, sub, visit)
			continue
		}
		if c.ArgsUsage != "" {
			name += " " + c.ArgsUsage
		}
		visit(name, c)
	}
}

// customCELFunctions returns the sorted names of the functions HocageLibrary
// adds on top of the base CEL environment.
func customCELFunctions() ([]string, error) {
	full, err := NewCELEnv()
	if err != nil {
		return nil, err
	}
	base, err := cel.NewEnv(baseEnvOptions()...)
	if err != nil {
		return nil, err
	}
	baseFns := base.Functions()
	var names []string
	for name := range full.Functions() {
		if _, ok := baseFns[name]; !ok {
			names = append(names, name)
		}
	}
	slices.Sort(names)
	return names, nil
}

func formatCELFunctionList(names []string) []byte {
	return []byte(backtickJoin(names) + "\n")
}

// backtickJoin renders items as a comma-separated list of `code` spans.
func backtickJoin(items []string) string {
	quoted := make([]string, len(items))
	for i, s := range items {
		quoted[i] = "`" + s + "`"
	}
	return strings.Join(quoted, ", ")
}

// dashName renders a flag name with its `-`/`--` prefix.
func dashName(n string) string {
	if len(n) == 1 {
		return "-" + n
	}
	return "--" + n
}

func writeFlagLines(b *strings.Builder, flags []cli.Flag) {
	for _, f := range flags {
		var names []string
		for _, n := range f.Names() {
			names = append(names, dashName(n))
		}
		line := "- " + backtickJoin(names)
		if doc, ok := f.(cli.DocGenerationFlag); ok && doc.GetUsage() != "" {
			line += " — " + doc.GetUsage()
		}
		b.WriteString(line)
		b.WriteString("\n")
	}
}

// generateCLITable renders the compact command table for SKILL.md: one row per
// leaf command, full command path plus args and the Usage string.
func generateCLITable() []byte {
	var b strings.Builder
	b.WriteString("| Command | Description |\n|---------|-------------|\n")
	walkLeafCommands("hocage", newApp().VisibleCommands(), func(name string, c *cli.Command) {
		desc := c.Usage
		if len(c.Flags) > 0 {
			var names []string
			for _, f := range c.Flags {
				names = append(names, dashName(f.Names()[0]))
			}
			desc += " (flags: " + backtickJoin(names) + ")"
		}
		fmt.Fprintf(&b, "| `%s` | %s |\n", name, desc)
	})
	return []byte(b.String())
}

func gendocsCommand() *cli.Command {
	return &cli.Command{
		Name:   "gendocs",
		Usage:  "Regenerate docs derived from the source (run via go generate)",
		Hidden: true,
		Action: gendocsAction,
	}
}

func gendocsAction(ctx context.Context, cmd *cli.Command) error {
	for _, tgt := range genTargets() {
		current, want, err := renderTarget(tgt)
		if err != nil {
			return err
		}
		if bytes.Equal(current, want) {
			continue
		}
		if err := os.WriteFile(tgt.Path, want, 0o644); err != nil {
			return err
		}
		fmt.Fprintf(os.Stderr, "updated %s\n", tgt.Path)
	}
	return nil
}

// renderTarget reads tgt's committed content and renders the up-to-date
// content, sharing the staleness contract between gendocsAction and
// TestGeneratedDocsUpToDate.
func renderTarget(tgt genTarget) (current, want []byte, err error) {
	current, err = os.ReadFile(tgt.Path)
	if err != nil {
		return nil, nil, fmt.Errorf("gendocs must run from the repo root: %w", err)
	}
	want, err = tgt.Render(current)
	if err != nil {
		return nil, nil, fmt.Errorf("%s: %w", tgt.Path, err)
	}
	return current, want, nil
}

// injectSection replaces the text between "<!-- gen:NAME:start -->" and
// "<!-- gen:NAME:end -->" in content with gen, keeping the markers.
func injectSection(content []byte, name string, gen []byte) ([]byte, error) {
	start := fmt.Sprintf("<!-- gen:%s:start -->", name)
	end := fmt.Sprintf("<!-- gen:%s:end -->", name)
	re := regexp.MustCompile(`(?s)` + regexp.QuoteMeta(start) + `.*?` + regexp.QuoteMeta(end))
	if !re.Match(content) {
		return nil, fmt.Errorf("markers %s / %s not found", start, end)
	}
	replacement := start + "\n" + string(bytes.TrimSpace(gen)) + "\n" + end
	// ReplaceAllLiteral: generated text may contain "$" (e.g. $XDG_CONFIG_HOME),
	// which ReplaceAll would misinterpret as a capture-group reference.
	return re.ReplaceAllLiteral(content, []byte(replacement)), nil
}

func generateEventDocs() []byte {
	var b strings.Builder
	b.WriteString(generatedHeader("schema.go"))
	b.WriteString("\n")
	b.WriteString("# Event Types and Output Schemas\n\n")
	b.WriteString("The authoritative reference for all hocage event types and their respond output schemas.\n\n")

	b.WriteString(`## hookSpecificOutput

Many events accept a ` + "`hookSpecificOutput`" + ` object for event-specific output (see each
event section below for its nested fields). Inside it, ` + "`hookEventName`" + ` must exactly
match the event name that triggered the hook (e.g. ` + "`PreToolUse`" + `). ` + "`hocage hooks check`" + `
validates nested fields, types, and enum values, using dotted paths in error messages
(e.g. ` + "`hookSpecificOutput.permissionDecision`" + `).

`)

	b.WriteString("## Common Output Fields\n\nEvery event accepts these top-level fields in addition to its own:\n\n")
	writeFieldTableHeader(&b)
	for _, f := range commonOutputFields {
		writeFieldRow(&b, "", f, false)
	}
	b.WriteString("\n")

	b.WriteString("## Events with Output Fields\n\n")
	for _, ev := range eventDefs {
		if len(ev.Fields) == 0 {
			continue
		}
		fmt.Fprintf(&b, "### %s\n\n%s\n\n", ev.Name, ev.Doc)
		writeFieldTableHeader(&b)
		for _, f := range ev.Fields {
			writeFieldRow(&b, "", f, false)
		}
		b.WriteString("\n")
		for _, f := range ev.Fields {
			if f.Fields != nil {
				fmt.Fprintf(&b, "`%s` nested fields:\n\n", f.Name)
				writeFieldTableHeader(&b)
				for _, nested := range f.Fields {
					writeFieldRow(&b, "", nested, true)
				}
				b.WriteString("\n")
			}
		}
		if ev.Example != "" {
			b.WriteString(ev.Example)
			b.WriteString("\n\n")
		}
	}

	b.WriteString(`## Events with No Event-Specific Output Fields

These events are observe-only (the common output fields above still apply). Use
them with ` + "`command` or `http`" + ` actions (not ` + "`respond`" + `), or use ` + "`respond`" + ` with an
empty object.

| Event | Description |
|-------|-------------|
`)
	for _, ev := range eventDefs {
		if len(ev.Fields) == 0 {
			fmt.Fprintf(&b, "| `%s` | %s |\n", ev.Name, ev.Doc)
		}
	}
	b.WriteString("\n")

	b.WriteString(`## Event Input Structure

All events receive a JSON object on stdin with these common fields:
` + fence + `json
{
  "hook_event_name": "<EventName>",
  "session_id": "...",
  "transcript_path": "/path/to/session.jsonl",
  "cwd": "/current/working/directory",
  "permission_mode": "default",
  "prompt_id": "...",
  "effort": { "level": "high" }
}
` + fence + `
(` + "`agent_id`/`agent_type`" + ` appear additionally when the hook fires inside a subagent.)

Tool events (PreToolUse, PostToolUse, etc.) also include:
` + fence + `json
{
  "hook_event_name": "PreToolUse",
  "tool_name": "Bash",
  "tool_input": { "command": "ls -la" },
  "tool_use_id": "toolu_..."
}
` + fence + `
PostToolUse additionally carries the result as ` + "`tool_response`" + `, and
PostToolUseFailure carries ` + "`error`" + `.

UserPromptSubmit includes:
` + fence + `json
{
  "hook_event_name": "UserPromptSubmit",
  "prompt": "the user's prompt text"
}
` + fence + `

Access these via ` + "`event.hook_event_name`, `event.tool_name`, `event.tool_input.command`" + `, etc. in CEL expressions.
`)

	return []byte(b.String())
}

func writeFieldTableHeader(b *strings.Builder) {
	b.WriteString("| Field | Type | Allowed Values | Description |\n")
	b.WriteString("|-------|------|----------------|-------------|\n")
}

// writeFieldRow writes one table row. When flatten is true, object fields with
// a nested schema also emit their children as dotted-path rows (e.g.
// decision.behavior); otherwise nested schemas are summarized as "see below".
func writeFieldRow(b *strings.Builder, prefix string, f FieldDef, flatten bool) {
	name := prefix + f.Name
	fmt.Fprintf(b, "| `%s` | %s | %s | %s |\n", name, f.Type, allowedValues(f), f.Doc)
	if flatten && f.Fields != nil {
		for _, nested := range f.Fields {
			writeFieldRow(b, name+".", nested, true)
		}
	}
}

func allowedValues(f FieldDef) string {
	switch {
	case len(f.Enum) > 0:
		return backtickJoin(f.Enum)
	case f.Type == FieldTypeBool:
		return "`true`/`false`"
	case f.Fields != nil:
		return "see below"
	default:
		return "any"
	}
}
